name: Auto Update M3U

on:
  schedule:
    - cron: '*/15 * * * *'  # প্রতি ১৫ মিনিটে চলবে
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Required Packages
        run: pip install requests

      - name: Run Update Script
        run: python update.py

      - name: Commit Updated File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add ayna
          git commit -m "🔄 Auto update Ayna file" || echo "No changes to commit"
          git push
