name: Manual M3U Update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Private Repository
        uses: actions/checkout@v4

      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          repository: srhady/Hady
          token: ${{ secrets.PAT_TOKEN }}
          path: target_repo

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Execute Script
        run: |
          if [ -f "target_repo/akash_live.m3u" ]; then
            cp target_repo/akash_live.m3u .
          fi
          python akash.py
          cp akash_live.m3u target_repo/

      - name: Commit and Push to Target
        run: |
          cd target_repo
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add akash_live.m3u
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update M3U Playlist" && git push)
